---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: nginx-demo-dev
  namespace: nginx-demo
  labels:
    app: nginx-demo
customVersion: v1beta2
spec:
  v1beta2:
    image: jtimberman/nginx-demo:latest
    count: 2
    service:
      name: nginx-demo
      topology: standalone
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  selector:
    habitat-name: nginx-demo-dev
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
